// <auto-generated />
using System;
using HBA.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Inventory.Infrastructure.Migrations;

[DbContext(typeof(InventoryDbContext))]
[Migration("20250605000000_InitialInventory")]
partial class InitialInventory
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("inventory")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "inventory");
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Locations.FulfillmentLocation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("CreatedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("OwnerId").HasColumnType("uuid");
            b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
            b.HasKey("Id");
            b.HasIndex("OwnerId");
            b.ToTable("fulfillment_locations", "inventory");
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Stock.InventoryItem", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("LocationId").HasColumnType("uuid");
            b.Property<int>("OnHand").HasColumnType("integer");
            b.Property<int>("ReorderThreshold").HasColumnType("integer");
            b.Property<string>("Sku").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("sku");
            b.HasKey("Id");
            b.HasIndex("Sku");
            b.HasIndex("Sku", "LocationId").IsUnique();
            b.ToTable("inventory_items", "inventory");
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Stock.StockReservation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("ExpiresAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("InventoryItemId").HasColumnType("uuid");
            b.Property<Guid>("OrderId").HasColumnType("uuid");
            b.Property<int>("Quantity").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("InventoryItemId");
            b.HasIndex("OrderId");
            b.ToTable("stock_reservations", "inventory");
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Locations.FulfillmentLocation", b =>
        {
            b.OwnsOne("HBA.Inventory.Domain.Locations.Address", "Address", b1 =>
            {
                b1.Property<Guid>("FulfillmentLocationId").HasColumnType("uuid");
                b1.Property<string>("City").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)").HasColumnName("address_city");
                b1.Property<string>("Country").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("address_country");
                b1.Property<double?>("Latitude").HasColumnType("double precision").HasColumnName("address_latitude");
                b1.Property<string>("Line").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("address_line");
                b1.Property<double?>("Longitude").HasColumnType("double precision").HasColumnName("address_longitude");
                b1.HasKey("FulfillmentLocationId");
                b1.ToTable("fulfillment_locations", "inventory");
                b1.WithOwner().HasForeignKey("FulfillmentLocationId");
            });

            b.Navigation("Address").IsRequired();
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Stock.StockReservation", b =>
        {
            b.HasOne("HBA.Inventory.Domain.Stock.InventoryItem", null)
                .WithMany("Reservations")
                .HasForeignKey("InventoryItemId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HBA.Inventory.Domain.Stock.InventoryItem", b =>
        {
            b.Navigation("Reservations");
        });
#pragma warning restore 612, 618
    }
}
