<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Protobuf Include="..\..\proto\order\v1\order.proto" GrpcServices="Both" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HBA.Ordering.Contracts\HBA.Ordering.Contracts.csproj" />
    <ProjectReference Include="..\..\..\services\marketplace\order-service\src\HBA.Order.Contracts\HBA.Order.Contracts.csproj" />
    <ProjectReference Include="..\..\common\HBA.Shared.Hosting\HBA.Shared.Hosting.csproj" />
  </ItemGroup>
</Project>
