<Project Sdk="Microsoft.NET.Sdk">

  <!-- Infrastructure : EF Core, repositories, hasher BCrypt, JWT, TOTP, DI du
       module. Référence Application + Domain + Contracts + BuildingBlocks.Infra. -->
  <ItemGroup>
    <ProjectReference Include="..\HBA.Identity.Domain\HBA.Identity.Domain.csproj" />
    <ProjectReference Include="..\HBA.Identity.Application\HBA.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\contracts\HBA.Identity.Contracts\HBA.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.Infrastructure\HBA.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Otp.NET" />
  </ItemGroup>

</Project>
