// <auto-generated />
using System;
using HBA.Delivery.Pricing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Delivery.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryPricingDbContext))]
    partial class DeliveryPricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery_pricing")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBA.Delivery.Pricing.Domain.Aggregates.DeliveryQuote.DeliveryQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConsumedByDeliveryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<long>("Discount")
                        .HasColumnType("bigint");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PricingVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("delivery_quotes", "delivery_pricing");
                });

            modelBuilder.Entity("HBA.Delivery.Pricing.Domain.Entities.DeliveryZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("GeometryRef")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("Serviceable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("delivery_zones", "delivery_pricing");
                });

            modelBuilder.Entity("HBA.Delivery.Pricing.Domain.Entities.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BaseFee")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaxFee")
                        .HasColumnType("bigint");

                    b.Property<long>("MinFee")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("PerKmFee")
                        .HasColumnType("bigint");

                    b.Property<long>("PerMinuteFee")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ServiceLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("SurgeMultiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("pricing_rules", "delivery_pricing");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredOnUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredOnUtc");

                    b.ToTable("audit_entries", "delivery_pricing");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_dead_letters")
                        .HasFilter("\"DeadLetteredOnUtc\" IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL AND \"DeadLetteredOnUtc\" IS NULL");

                    b.ToTable("outbox_messages", "delivery_pricing");
                });

            modelBuilder.Entity("HBA.Delivery.Pricing.Domain.Aggregates.DeliveryQuote.DeliveryQuote", b =>
                {
                    b.OwnsOne("HBA.Delivery.Pricing.Domain.ValueObjects.PriceBreakdown", "Components", b1 =>
                        {
                            b1.Property<Guid>("DeliveryQuoteId")
                                .HasColumnType("uuid");

                            b1.Property<long>("BaseFee")
                                .HasColumnType("bigint");

                            b1.Property<long>("Discount")
                                .HasColumnType("bigint");

                            b1.Property<long>("DistanceFee")
                                .HasColumnType("bigint");

                            b1.Property<long>("MinuteFee")
                                .HasColumnType("bigint");

                            b1.Property<long>("SurgeFee")
                                .HasColumnType("bigint");

                            b1.HasKey("DeliveryQuoteId");

                            b1.ToTable("delivery_quotes", "delivery_pricing");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryQuoteId");
                        });

                    b.OwnsOne("HBA.Delivery.Pricing.Domain.ValueObjects.GeoPoint", "Dropoff", b1 =>
                        {
                            b1.Property<Guid>("DeliveryQuoteId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("DeliveryQuoteId");

                            b1.ToTable("delivery_quotes", "delivery_pricing");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryQuoteId");
                        });

                    b.OwnsOne("HBA.Delivery.Pricing.Domain.ValueObjects.GeoPoint", "Pickup", b1 =>
                        {
                            b1.Property<Guid>("DeliveryQuoteId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("DeliveryQuoteId");

                            b1.ToTable("delivery_quotes", "delivery_pricing");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryQuoteId");
                        });

                    b.Navigation("Components")
                        .IsRequired();

                    b.Navigation("Dropoff")
                        .IsRequired();

                    b.Navigation("Pickup")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
