// <auto-generated />
using System;
using HBA.Marketplace.ReturnRefund.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Marketplace.ReturnRefund.Infrastructure.Migrations
{
    [DbContext(typeof(ReturnRefundDbContext))]
    partial class ReturnRefundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("return_refund")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReturnId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("refunds", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.RefundAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RefundId");

                    b.ToTable("refund_attempts", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MediaId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_evidence", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("InspectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_inspections", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AlreadyReturnedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionDeclared")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConditionInspected")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveredQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("UnitPaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_items", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedRefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CustomerComment")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedRefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResolutionRequested")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReturnShippingPayer")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SellerOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ReturnNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId", "CreatedAtUtc");

                    b.HasIndex("SellerId", "Status");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("return_requests", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnShipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_shipments", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId", "OccurredAtUtc");

                    b.ToTable("return_status_history", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Infrastructure.Persistence.ReturnIdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReturnRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("ReturnRequestId")
                        .IsUnique();

                    b.ToTable("idempotency_keys", "return_refund");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredOnUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredOnUtc");

                    b.ToTable("audit_entries", "return_refund");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_dead_letters")
                        .HasFilter("\"DeadLetteredOnUtc\" IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL AND \"DeadLetteredOnUtc\" IS NULL");

                    b.ToTable("outbox_messages", "return_refund");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.Refund", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("Refunds")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.RefundBreakdown", "Breakdown", b1 =>
                        {
                            b1.Property<Guid>("RefundId")
                                .HasColumnType("uuid");

                            b1.HasKey("RefundId");

                            b1.ToTable("refunds", "return_refund");

                            b1.WithOwner()
                                .HasForeignKey("RefundId");

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "DiscountAllocation", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("discount_allocation_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("discount_allocation_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "Items", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("items_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("items_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "OriginalShipping", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("original_shipping_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("original_shipping_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "PreviousRefunds", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("previous_refunds_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("previous_refunds_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "RestockingFee", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("restocking_fee_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("restocking_fee_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "ReturnShippingCharge", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("return_shipping_charge_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("return_shipping_charge_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.Money", "Tax", b2 =>
                                {
                                    b2.Property<Guid>("RefundBreakdownRefundId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("tax_currency");

                                    b2.HasKey("RefundBreakdownRefundId");

                                    b2.ToTable("refunds", "return_refund");

                                    b2.WithOwner()
                                        .HasForeignKey("RefundBreakdownRefundId");
                                });

                            b1.Navigation("DiscountAllocation")
                                .IsRequired();

                            b1.Navigation("Items")
                                .IsRequired();

                            b1.Navigation("OriginalShipping")
                                .IsRequired();

                            b1.Navigation("PreviousRefunds")
                                .IsRequired();

                            b1.Navigation("RestockingFee")
                                .IsRequired();

                            b1.Navigation("ReturnShippingCharge")
                                .IsRequired();

                            b1.Navigation("Tax")
                                .IsRequired();
                        });

                    b.Navigation("Breakdown")
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.RefundAttempt", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.Refund", null)
                        .WithMany("Attempts")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnEvidence", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("Evidence")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnInspection", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("Inspections")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnItem", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("Items")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", b =>
                {
                    b.OwnsOne("HBA.Marketplace.ReturnRefund.Domain.ValueObjects.PolicySnapshot", "PolicySnapshot", b1 =>
                        {
                            b1.Property<Guid>("ReturnRequestId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowRefundOnly")
                                .HasColumnType("boolean")
                                .HasColumnName("policy_allow_refund_only");

                            b1.Property<bool>("AllowReturn")
                                .HasColumnType("boolean")
                                .HasColumnName("policy_allow_return");

                            b1.Property<string>("PolicyId")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("policy_id");

                            b1.Property<bool>("RequireEvidence")
                                .HasColumnType("boolean")
                                .HasColumnName("policy_require_evidence");

                            b1.Property<bool>("RequireInspection")
                                .HasColumnType("boolean")
                                .HasColumnName("policy_require_inspection");

                            b1.Property<decimal>("RestockingFeePercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("policy_restocking_fee_percent");

                            b1.Property<int>("ReturnWindowDays")
                                .HasColumnType("integer")
                                .HasColumnName("policy_return_window_days");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("policy_version");

                            b1.HasKey("ReturnRequestId");

                            b1.ToTable("return_requests", "return_refund");

                            b1.WithOwner()
                                .HasForeignKey("ReturnRequestId");
                        });

                    b.Navigation("PolicySnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnShipment", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("Shipments")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnStatusHistory", b =>
                {
                    b.HasOne("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", null)
                        .WithMany("History")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.Refund", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("HBA.Marketplace.ReturnRefund.Domain.Aggregates.ReturnRequest.ReturnRequest", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("History");

                    b.Navigation("Inspections");

                    b.Navigation("Items");

                    b.Navigation("Refunds");

                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
