// <auto-generated />
using System;
using System.Collections.Generic;
using HBA.Communication.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Communication.Infrastructure.Migrations;

[DbContext(typeof(MessagingDbContext))]
[Migration("20250618000000_InitialMessaging")]
partial class InitialMessaging
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("messaging")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "messaging");
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.Conversation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid?>("ContextId").HasColumnType("uuid");
            b.Property<string>("ContextType").HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<DateTime>("LastMessageAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.HasKey("Id");
            b.ToTable("conversations", "messaging");
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.ConversationParticipant", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("ConversationId").HasColumnType("uuid");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("ConversationId");
            b.HasIndex("UserId");
            b.ToTable("conversation_participants", "messaging");
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.Message", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("ConversationId").HasColumnType("uuid");
            b.Property<string>("Body").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ReadAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("SenderId").HasColumnType("uuid");
            b.Property<List<string>>("_attachments").IsRequired().HasColumnType("text[]").HasColumnName("attachments");
            b.HasKey("Id");
            b.HasIndex("ConversationId");
            b.ToTable("conversation_messages", "messaging");
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.ConversationParticipant", b =>
        {
            b.HasOne("HBA.Communication.Domain.Conversations.Conversation", null)
                .WithMany("Participants")
                .HasForeignKey("ConversationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.Message", b =>
        {
            b.HasOne("HBA.Communication.Domain.Conversations.Conversation", null)
                .WithMany("Messages")
                .HasForeignKey("ConversationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HBA.Communication.Domain.Conversations.Conversation", b =>
        {
            b.Navigation("Messages");
            b.Navigation("Participants");
        });
#pragma warning restore 612, 618
    }
}
