// <auto-generated />
using System;
using System.Collections.Generic;
using HBA.Engagement.Recommendations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Engagement.Recommendations.Infrastructure.Migrations;

[DbContext(typeof(RecommendationsDbContext))]
[Migration("20250623000000_InitialRecommendations")]
partial class InitialRecommendations
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("recommendations")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "recommendations");
        });

        modelBuilder.Entity("HBA.Engagement.Recommendations.Domain.Recommendations.Recommendation", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid?>("ContextProductId").HasColumnType("uuid");
            b.Property<DateTime>("GeneratedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<double>("Score").HasColumnType("double precision");
            b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
            b.Property<Guid?>("UserId").HasColumnType("uuid");
            b.Property<List<Guid>>("_recommendedProductIds").IsRequired().HasColumnType("uuid[]").HasColumnName("recommended_product_ids");
            b.HasKey("Id");
            b.HasIndex("Type", "ContextProductId");
            b.HasIndex("Type", "UserId");
            b.ToTable("recommendations", "recommendations");
        });
#pragma warning restore 612, 618
    }
}
