<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\HBA.Delivery.Tracking.Application\HBA.Delivery.Tracking.Application.csproj" />
    <ProjectReference Include="..\HBA.Delivery.Tracking.Infrastructure\HBA.Delivery.Tracking.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.Hosting\HBA.Shared.Hosting.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\contracts\HBA.Tracking.Contracts.Grpc\HBA.Tracking.Contracts.Grpc.csproj" />
  </ItemGroup>

</Project>
