services:
  postgres:
    image: postgres:latest
    container_name: hba-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB:        postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - hba-backend

  # REDIS POUR LE CASH
  redis:
    image: redis:8-alpine
    container_name: hba-redis
    restart: unless-stopped
    command:
      ["redis-server","--requirepass","${REDIS_PASSWORD}","--appendonly","yes"]
    volumes:
      - redis_data:/data
    networks:
      - hba-backend

  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: hba-redis-ui
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - hba-backend

  kafka:
    image: confluentinc/cp-kafka:8.3.1
    container_name: hba-kafka
    hostname: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      # Configuration KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_LISTENERS: >
        INTERNAL://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:29093,
        EXTERNAL://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:29092,
        EXTERNAL://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Configuration pour un seul broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      # Identifiant fixe du cluster KRaft
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
        test:
          [
            "CMD-SHELL",
            "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1"
          ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 30s

    networks:
      - hba-backend

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hba-kafka-ui
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_NAME: hba-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    networks:
      - hba-backend

  minio:
    image: minio/minio:latest
    container_name: hba-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_data:/data

    networks:
      - hba-backend
      - hba-proxy


volumes:

  postgres_data:
  redis_data:
  kafka_data:
  minio_data:


networks:
  hba-backend:
    name: hba-backend

  hba-proxy:
    name: hba-proxy
