name: hba-analytics-service

services:
  postgres:
    extends:
      file: ../../../docker-compose.dev.yml
      service: postgres

  kafka:
    extends:
      file: ../../../docker-compose.dev.yml
      service: kafka

  analytics-service:
    ports:
      - "8080:8080"
      - "9090:9090"

volumes:
  postgres-data:
