<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\HBA.Delivery.Proof.Application\HBA.Delivery.Proof.Application.csproj" />
    <ProjectReference Include="..\HBA.Delivery.Proof.Infrastructure\HBA.Delivery.Proof.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.Hosting\HBA.Shared.Hosting.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\contracts\HBA.ProofOfDelivery.Contracts.Grpc\HBA.ProofOfDelivery.Contracts.Grpc.csproj" />
  </ItemGroup>

</Project>
