<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\shared\contracts\HBA.Routes.Contracts\HBA.Routes.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.IntegrationEvents\HBA.Shared.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
