// <auto-generated />
using System;
using HBA.Financial.Payments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Financial.Payments.Infrastructure.Migrations;

[DbContext(typeof(PaymentsDbContext))]
[Migration("20250609000000_InitialPayments")]
partial class InitialPayments
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("payments")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "payments");
        });

        modelBuilder.Entity("HBA.Financial.Payments.Domain.Payments.Payment", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("BuyerId").HasColumnType("uuid");
            b.Property<DateTime?>("CapturedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("Method").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid>("OrderId").HasColumnType("uuid");
            b.Property<string>("Provider").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("ProviderReference").HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.HasKey("Id");
            b.HasIndex("OrderId");
            b.HasIndex("Status");
            b.ToTable("payments", "payments");
        });

        modelBuilder.Entity("HBA.Financial.Payments.Domain.Payments.Payment", b =>
        {
            b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "Amount", b1 =>
            {
                b1.Property<Guid>("PaymentId").HasColumnType("uuid");
                b1.Property<decimal>("Amount").HasColumnType("numeric(18,2)").HasColumnName("amount");
                b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("currency");
                b1.HasKey("PaymentId");
                b1.ToTable("payments", "payments");
                b1.WithOwner().HasForeignKey("PaymentId");
            });

            b.Navigation("Amount").IsRequired();
        });
#pragma warning restore 612, 618
    }
}
