// <auto-generated />
using System;
using HBA.Communication.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Communication.Notifications.Infrastructure.Migrations;

[DbContext(typeof(NotificationsDbContext))]
[Migration("20250613000000_InitialNotifications")]
partial class InitialNotifications
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("notifications")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "notifications");
        });

        modelBuilder.Entity("HBA.Communication.Notifications.Domain.Notifications.Notification", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Body").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<string>("Channel").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ReadAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("RelatedEntityId").HasColumnType("uuid");
            b.Property<string>("RelatedEntityType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<Guid>("RecipientUserId").HasColumnType("uuid");
            b.Property<DateTime?>("SentAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<string>("Subject").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.HasKey("Id");
            b.HasIndex("RecipientUserId", "Status");
            b.ToTable("notifications", "notifications");
        });
#pragma warning restore 612, 618
    }
}
