// <auto-generated />
using System;
using HBA.Orders.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Orders.Infrastructure.Migrations;

[DbContext(typeof(OrderingDbContext))]
[Migration("20250608000000_InitialOrdering")]
partial class InitialOrdering
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("ordering")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "ordering");
        });

        modelBuilder.Entity("HBA.Orders.Domain.Orders.Order", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<Guid>("BuyerId").HasColumnType("uuid");
            b.Property<string>("CancellationReason").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<Guid>("CartId").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
            b.Property<decimal>("GrandTotal").HasColumnType("numeric(18,2)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<decimal>("Subtotal").HasColumnType("numeric(18,2)");
            b.Property<decimal>("TotalPlatformDiscount").HasColumnType("numeric(18,2)");
            b.Property<decimal>("TotalSellerDiscount").HasColumnType("numeric(18,2)");
            b.HasKey("Id");
            b.HasIndex("BuyerId", "Status");
            b.ToTable("orders", "ordering");
        });

        modelBuilder.Entity("HBA.Orders.Domain.Orders.OrderLine", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<decimal>("FinalUnitPrice").HasColumnType("numeric(18,2)");
            b.Property<Guid>("OfferId").HasColumnType("uuid");
            b.Property<Guid>("OrderId").HasColumnType("uuid");
            b.Property<decimal>("PlatformDiscount").HasColumnType("numeric(18,2)");
            b.Property<Guid>("ProductId").HasColumnType("uuid");
            b.Property<int>("Quantity").HasColumnType("integer");
            b.Property<decimal>("SellerDiscount").HasColumnType("numeric(18,2)");
            b.Property<Guid>("SellerId").HasColumnType("uuid");
            b.Property<Guid>("ShipFromLocationId").HasColumnType("uuid");
            b.Property<string>("Sku").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<decimal>("UnitBasePrice").HasColumnType("numeric(18,2)");
            b.HasKey("Id");
            b.HasIndex("OrderId");
            b.HasIndex("SellerId");
            b.ToTable("order_lines", "ordering");
        });

        modelBuilder.Entity("HBA.Orders.Domain.Orders.OrderLine", b =>
        {
            b.HasOne("HBA.Orders.Domain.Orders.Order", null)
                .WithMany("Lines")
                .HasForeignKey("OrderId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HBA.Orders.Domain.Orders.Order", b =>
        {
            b.Navigation("Lines");
        });
#pragma warning restore 612, 618
    }
}
