name: hba-identity-service

services:
  kafka:
    extends:
      file: ../../../docker-compose.dev.yml
      service: kafka

  postgres:
    extends:
      file: ../../../docker-compose.dev.yml
      service: postgres

  redis:
    extends:
      file: ../../../docker-compose.dev.yml
      service: redis

  identity-service:
    extends:
      file: ../../../docker-compose.dev.yml
      service: identity-service
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9090:9090"

volumes:
  postgres-data:

networks:
  hba-backend:
