using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Catalog.Infrastructure.Migrations
{
    /// <summary>
    /// ═════════════════════════════════════════════════════════════════════════
    /// LE JOURNAL DE QUI A FAIT QUOI — <c>catalog.audit_entries</c> (lot 7.1).
    ///
    /// Une ligne par entité mutée, écrite dans la MÊME transaction que la mutation
    /// par <c>ModuleDbContext.SaveChangesAsync</c>. Voir <c>AuditEntry</c> pour le
    /// raisonnement d'ensemble — notamment pourquoi ce n'est pas une colonne
    /// <c>LastModifiedBy</c> sur chaque table.
    ///
    /// ÉCRITE À LA MAIN. <c>[DbContext]</c> et <c>[Migration]</c> sont portés par
    /// la classe, il n'y a pas de <c>.Designer.cs</c>, et le snapshot est mis à jour
    /// dans le même commit. Si l'un des deux attributs manquait, EF ignorerait cette
    /// migration EN SILENCE et la table n'existerait pas.
    ///
    /// <c>ActorUserId</c> EST NULLABLE, ET C'EST UNE INFORMATION.
    ///
    /// Un consommateur Kafka, un appel gRPC interne, un travail de fond : la mutation
    /// n'a pas de personne derrière elle. Une contrainte NOT NULL forcerait à
    /// inventer un identifiant.
    ///
    /// AUCUNE REPRISE DE DONNÉES.
    ///
    /// Le journal commence ici. Rien ne permet de reconstituer rétroactivement qui a
    /// fait quoi — l'information n'a jamais été écrite. Une table pré-remplie avec un
    /// acteur inventé serait pire que vide : elle donnerait des réponses fausses à
    /// des questions sérieuses.
    ///
    /// <c>IF NOT EXISTS</c> : une base alignée à la main ne doit pas empêcher le
    /// service de démarrer, les migrations s'appliquant au démarrage.
    /// ═════════════════════════════════════════════════════════════════════════
    /// </summary>
    [DbContext(typeof(HBA.Catalog.Infrastructure.Persistence.CatalogDbContext))]
    [Migration("20260828000300_JournalDAuditCatalog")]
    public partial class JournalDAuditCatalog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS catalog.audit_entries (
                    ""Id""             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""EntityType""     character varying(120) NOT NULL,
                    ""EntityId""       character varying(200) NOT NULL,
                    ""Operation""      integer NOT NULL,
                    ""ActorUserId""    uuid NULL,
                    ""ActorType""      character varying(32) NOT NULL,
                    ""CorrelationId""  character varying(100) NULL,
                    ""OccurredOnUtc""  timestamp with time zone NOT NULL
                );");

            // « qu'est-il arrivé à CETTE ligne » — la question d'un litige sur une
            // fiche, une offre, une course, un paiement précis.
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_audit_entries_EntityType_EntityId_OccurredOnUtc""
                    ON catalog.audit_entries (""EntityType"", ""EntityId"", ""OccurredOnUtc"");");

            // « qu'a fait CETTE personne » — la question qu'on pose après un incident.
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_audit_entries_ActorUserId_OccurredOnUtc""
                    ON catalog.audit_entries (""ActorUserId"", ""OccurredOnUtc"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // IRRÉVERSIBLE EN PRATIQUE : le retour arrière efface le journal, et
            // rien ne le reconstitue. Acceptable pour un retour immédiat après
            // livraison, jamais pour une réparation à froid.
            migrationBuilder.Sql("DROP TABLE IF EXISTS catalog.audit_entries;");
        }
    }
}
