// <auto-generated />
using System;
using System.Collections.Generic;
using HBA.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBA.Catalog.Domain.Attributes.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("attribute_definitions", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Attributes.CategoryAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("Variant")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("category_attributes", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Brands.BrandRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_brand_requests_pending")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.ToTable("brand_requests", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attribute_schema");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Slug");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Offers.ProductOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fulfillment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("HandlingTimeDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PromotionEndsOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProviderFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipFromLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.HasIndex("VariantId");

                    b.HasIndex("StoreId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_offers_store_variant")
                        .HasFilter("\"Status\" <> 'Archived'");

                    b.ToTable("product_offers", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ean")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<Guid?>("ProductGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("PublishedRevisionId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.HasIndex("StoreId");

                    b.HasIndex("SellerId", "Status");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatteryHealthPercentage")
                        .HasColumnType("integer");

                    b.Property<bool?>("BatteryReplaced")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FunctionalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Grade")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<bool>("HasOriginalAccessories")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOriginalPackaging")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefurbished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RefurbishedBySellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefurbishedByType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<List<string>>("RefurbishmentOperations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("refurbishment_operations");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("product_conditions", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductDefect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.ToTable("product_condition_defects", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LegacyExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_media", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_product_revisions_published_slug")
                        .HasFilter("\"Status\" = 'Published'");

                    b.HasIndex("Status");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("product_revisions", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("product_specifications", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductSpecificationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.ToTable("product_specification_groups", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("VariantAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variant_attributes");

                    b.Property<int>("WeightGrams")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product_variants", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Reviews.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevisionVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("ProductId", "ReviewedAtUtc");

                    b.ToTable("product_reviews", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Reviews.ProductReviewReason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("product_review_reasons", "catalog");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Scope")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Key", "Scope", "Endpoint");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", "catalog");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Inbox.ConsumerInboxEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "ConsumerName");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_consumer_inbox_processed_at");

                    b.ToTable("consumer_inbox", "catalog");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredOnUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredOnUtc");

                    b.ToTable("audit_entries", "catalog");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_dead_letters")
                        .HasFilter("\"DeadLetteredOnUtc\" IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL AND \"DeadLetteredOnUtc\" IS NULL");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Offers.ProductOffer", b =>
                {
                    b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "BuyerPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductOfferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BuyerPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BuyerPriceCurrency");

                            b1.HasKey("ProductOfferId");

                            b1.ToTable("product_offers", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductOfferId");
                        });

                    b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "PromotionalPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductOfferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PromotionalPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PromotionalPriceCurrency");

                            b1.HasKey("ProductOfferId");

                            b1.ToTable("product_offers", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductOfferId");
                        });

                    b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "SellerPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductOfferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("SellerPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("ProductOfferId");

                            b1.ToTable("product_offers", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductOfferId");
                        });

                    b.Navigation("BuyerPrice")
                        .IsRequired();

                    b.Navigation("PromotionalPrice");

                    b.Navigation("SellerPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductCondition", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.ProductRevision", null)
                        .WithOne("Condition")
                        .HasForeignKey("HBA.Catalog.Domain.Products.ProductCondition", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductDefect", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.ProductCondition", null)
                        .WithMany("Defects")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductMedia", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.Product", null)
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductRevision", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.Product", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HBA.Catalog.Domain.Products.ProductPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("ProductRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<long>("BasePrice")
                                .HasColumnType("bigint")
                                .HasColumnName("base_price");

                            b1.Property<long?>("CompareAtPrice")
                                .HasColumnType("bigint")
                                .HasColumnName("compare_at_price");

                            b1.Property<long?>("CostPrice")
                                .HasColumnType("bigint")
                                .HasColumnName("cost_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<bool>("TaxIncluded")
                                .HasColumnType("boolean")
                                .HasColumnName("tax_included");

                            b1.Property<int>("TaxRate")
                                .HasColumnType("integer")
                                .HasColumnName("tax_rate");

                            b1.HasKey("ProductRevisionId");

                            b1.ToTable("product_revisions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductRevisionId");
                        });

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductSpecification", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.ProductSpecificationGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductSpecificationGroup", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.ProductRevision", null)
                        .WithMany("Specifications")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Reviews.ProductReviewReason", b =>
                {
                    b.HasOne("HBA.Catalog.Domain.Reviews.ProductReview", null)
                        .WithMany("Reasons")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.Product", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Revisions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductCondition", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductRevision", b =>
                {
                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("Specifications");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Products.ProductSpecificationGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HBA.Catalog.Domain.Reviews.ProductReview", b =>
                {
                    b.Navigation("Reasons");
                });
#pragma warning restore 612, 618
        }
    }
}
