// <auto-generated />
using System;
using HBA.Food.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Food.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20260812081143_InitialFood")]
    partial class InitialFood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("food")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBA.Food.Domain.Menus.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "DisplayOrder");

                    b.ToTable("menus", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "MenuId", "DisplayOrder");

                    b.ToTable("menu_items", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("FulfillmentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PausedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PreparationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("restaurants", "food");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_dead_letters")
                        .HasFilter("\"DeadLetteredOnUtc\" IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL AND \"DeadLetteredOnUtc\" IS NULL");

                    b.ToTable("outbox_messages", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.MenuItem", b =>
                {
                    b.OwnsOne("HBA.Food.Domain.Menus.ItemAvailability", "Availability", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsMarkedAvailable")
                                .HasColumnType("boolean")
                                .HasColumnName("AvailabilityIsAvailable");

                            b1.Property<DateTime?>("UnavailableUntilUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("AvailabilityUntilUtc");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.OwnsMany("HBA.Food.Domain.Menus.OptionGroup", "_optionGroups", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxSelections")
                                .HasColumnType("integer");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MinSelections")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("MenuItemId");

                            b1.ToTable("menu_option_groups", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");

                            b1.OwnsMany("HBA.Food.Domain.Menus.MenuOption", "_options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)");

                                    b2.Property<Guid>("OptionGroupId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("PriceDelta")
                                        .HasColumnType("numeric(18,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OptionGroupId");

                                    b2.ToTable("menu_options", "food");

                                    b2.WithOwner()
                                        .HasForeignKey("OptionGroupId");

                                    b2.OwnsOne("HBA.Food.Domain.Menus.ItemAvailability", "Availability", b3 =>
                                        {
                                            b3.Property<Guid>("MenuOptionId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("IsMarkedAvailable")
                                                .HasColumnType("boolean")
                                                .HasColumnName("AvailabilityIsAvailable");

                                            b3.Property<DateTime?>("UnavailableUntilUtc")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("AvailabilityUntilUtc");

                                            b3.HasKey("MenuOptionId");

                                            b3.ToTable("menu_options", "food");

                                            b3.WithOwner()
                                                .HasForeignKey("MenuOptionId");
                                        });

                                    b2.Navigation("Availability")
                                        .IsRequired();
                                });

                            b1.Navigation("_options");
                        });

                    b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BasePriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BasePriceCurrency");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("_optionGroups");
                });

            modelBuilder.Entity("HBA.Food.Domain.Restaurants.Restaurant", b =>
                {
                    b.OwnsMany("HBA.Food.Domain.Restaurants.ServiceHours", "_serviceHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("ClosesAt")
                                .HasColumnType("time without time zone");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<TimeOnly>("OpensAt")
                                .HasColumnType("time without time zone");

                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RestaurantId", "Day");

                            b1.ToTable("restaurant_service_hours", "food");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("_serviceHours");
                });
#pragma warning restore 612, 618
        }
    }
}
