// <auto-generated />
using System;
using HBA.Food.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Food.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20260818183403_SyncModel20260818183400")]
    partial class SyncModel20260818183400
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("food")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HBA.Food.Domain.Menus.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "DisplayOrder");

                    b.ToTable("menus", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RestaurantId", "DisplayOrder");

                    b.ToTable("menu_categories", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePublicUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegacyImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MenuCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("PreparationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreparationStationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "MenuCategoryId", "DisplayOrder");

                    b.ToTable("menu_items", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Orders.FoodOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("EstimatedPreparationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PickedUpAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("WasAutoAccepted")
                        .HasColumnType("boolean");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_food_orders_order");

                    b.HasIndex("RestaurantId", "Status");

                    b.ToTable("food_orders", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Restaurants.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptanceMode")
                        .HasColumnType("integer");

                    b.Property<bool>("BlocksOrdersWhenSaturated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("FulfillmentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LegacyLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoPublicUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaximumActiveOrders")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PausedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PayoutSellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PreparationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("restaurants", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Staff.RestaurantStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFounder")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_restaurant_staff_user");

                    b.HasIndex("RestaurantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_restaurant_staff_restaurant_user");

                    b.ToTable("restaurant_staff", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Stations.PreparationStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_preparation_stations_restaurant_code");

                    b.ToTable("preparation_stations", "food");
                });

            modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DeadLetteredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeadLetteredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_dead_letters")
                        .HasFilter("\"DeadLetteredOnUtc\" IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL AND \"DeadLetteredOnUtc\" IS NULL");

                    b.ToTable("outbox_messages", "food");
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.Menu", b =>
                {
                    b.OwnsOne("HBA.Food.Domain.Menus.MenuServingWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("MenuId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("AvailableFrom")
                                .HasColumnType("date")
                                .HasColumnName("AvailableFrom");

                            b1.Property<DateOnly?>("AvailableUntil")
                                .HasColumnType("date")
                                .HasColumnName("AvailableUntil");

                            b1.Property<TimeOnly?>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("EndTime");

                            b1.Property<TimeOnly?>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("MenuId");

                            b1.ToTable("menus", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });

            modelBuilder.Entity("HBA.Food.Domain.Menus.MenuItem", b =>
                {
                    b.OwnsOne("HBA.Food.Domain.Menus.ItemAvailability", "Availability", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsMarkedAvailable")
                                .HasColumnType("boolean")
                                .HasColumnName("AvailabilityIsAvailable");

                            b1.Property<DateTime?>("UnavailableUntilUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("AvailabilityUntilUtc");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.OwnsMany("HBA.Food.Domain.Menus.OptionGroup", "_optionGroups", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxSelections")
                                .HasColumnType("integer");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MinSelections")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("MenuItemId");

                            b1.ToTable("menu_option_groups", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");

                            b1.OwnsMany("HBA.Food.Domain.Menus.MenuOption", "_options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)");

                                    b2.Property<Guid>("OptionGroupId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("PriceDelta")
                                        .HasColumnType("numeric(18,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OptionGroupId");

                                    b2.ToTable("menu_options", "food");

                                    b2.WithOwner()
                                        .HasForeignKey("OptionGroupId");

                                    b2.OwnsOne("HBA.Food.Domain.Menus.ItemAvailability", "Availability", b3 =>
                                        {
                                            b3.Property<Guid>("MenuOptionId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("IsMarkedAvailable")
                                                .HasColumnType("boolean")
                                                .HasColumnName("AvailabilityIsAvailable");

                                            b3.Property<DateTime?>("UnavailableUntilUtc")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("AvailabilityUntilUtc");

                                            b3.HasKey("MenuOptionId");

                                            b3.ToTable("menu_options", "food");

                                            b3.WithOwner()
                                                .HasForeignKey("MenuOptionId");
                                        });

                                    b2.Navigation("Availability")
                                        .IsRequired();
                                });

                            b1.Navigation("_options");
                        });

                    b.OwnsOne("HBA.Shared.Domain.Primitives.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BasePriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BasePriceCurrency");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items", "food");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.Navigation("Availability")
                        .IsRequired();

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("_optionGroups");
                });

            modelBuilder.Entity("HBA.Food.Domain.Orders.FoodOrder", b =>
                {
                    b.OwnsMany("HBA.Food.Domain.Orders.FoodOrderItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<Guid>("FoodOrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("NameSnapshot")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<int>("PreparationMinutes")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("PreparationStationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("FoodOrderId");

                            b1.HasIndex("PreparationStationId");

                            b1.ToTable("food_order_items", "food");

                            b1.WithOwner()
                                .HasForeignKey("FoodOrderId");

                            b1.OwnsMany("HBA.Food.Domain.Orders.FoodOrderItemOption", "_options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("FoodOrderItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("GroupName")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)");

                                    b2.Property<Guid>("OptionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("OptionName")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)");

                                    b2.Property<decimal>("PriceDelta")
                                        .HasColumnType("numeric(18,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FoodOrderItemId");

                                    b2.ToTable("food_order_item_options", "food");

                                    b2.WithOwner()
                                        .HasForeignKey("FoodOrderItemId");
                                });

                            b1.Navigation("_options");
                        });

                    b.OwnsOne("HBA.Food.Domain.Orders.FoodOrderRejection", "Rejection", b1 =>
                        {
                            b1.Property<Guid>("FoodOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comment")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("RejectionComment");

                            b1.Property<int>("Reason")
                                .HasColumnType("integer")
                                .HasColumnName("RejectionReason");

                            b1.Property<DateTime>("RejectedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RejectedAtUtc");

                            b1.Property<Guid>("RejectedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("RejectedByUserId");

                            b1.HasKey("FoodOrderId");

                            b1.ToTable("food_orders", "food");

                            b1.WithOwner()
                                .HasForeignKey("FoodOrderId");
                        });

                    b.Navigation("Rejection");

                    b.Navigation("_items");
                });

            modelBuilder.Entity("HBA.Food.Domain.Restaurants.Restaurant", b =>
                {
                    b.OwnsMany("HBA.Food.Domain.Restaurants.ServiceHours", "_serviceHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("ClosesAt")
                                .HasColumnType("time without time zone");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<TimeOnly>("OpensAt")
                                .HasColumnType("time without time zone");

                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RestaurantId", "Day");

                            b1.ToTable("restaurant_service_hours", "food");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsMany("HBA.Food.Domain.Restaurants.SpecialOpeningHour", "_specialHours", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<TimeOnly?>("ClosesAt")
                                .HasColumnType("time without time zone");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean");

                            b1.Property<TimeOnly?>("OpensAt")
                                .HasColumnType("time without time zone");

                            b1.Property<string>("Reason")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("RestaurantId", "Date");

                            b1.ToTable("restaurant_special_hours", "food");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("_serviceHours");

                    b.Navigation("_specialHours");
                });

            modelBuilder.Entity("HBA.Food.Domain.Staff.RestaurantStaff", b =>
                {
                    b.OwnsMany("HBA.Food.Domain.Staff.StaffPermissionOverride", "_overrides", b1 =>
                        {
                            b1.Property<Guid>("RestaurantStaffId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Permission")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsGranted")
                                .HasColumnType("boolean");

                            b1.HasKey("RestaurantStaffId", "Permission");

                            b1.ToTable("restaurant_staff_permissions", "food");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantStaffId");
                        });

                    b.Navigation("_overrides");
                });
#pragma warning restore 612, 618
        }
    }
}
