<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HBA.Financial.Billing.Domain\HBA.Financial.Billing.Domain.csproj" />
    <ProjectReference Include="..\HBA.Financial.Billing.Contracts\HBA.Financial.Billing.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.Application\HBA.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\shared\common\HBA.Shared.IntegrationEvents\HBA.Shared.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Billing.UnitTests" />
  </ItemGroup>

</Project>
