<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Protobuf Include="..\..\proto\foodcart\v1\foodcart.proto" GrpcServices="Both" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\services\food\food-cart-service\src\HBA.Food.Cart.Contracts\HBA.Food.Cart.Contracts.csproj" />
    <ProjectReference Include="..\..\common\HBA.Shared.Hosting\HBA.Shared.Hosting.csproj" />
  </ItemGroup>
</Project>
