// <auto-generated />
using System;
using HBA.Financial.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HBA.Financial.Billing.Infrastructure.Migrations;

[DbContext(typeof(BillingDbContext))]
[Migration("20250614000000_InitialBilling")]
partial class InitialBilling
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("billing")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("HBA.Shared.Infrastructure.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("jsonb");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("ProcessedOnUtc");
            b.ToTable("outbox_messages", "billing");
        });

        modelBuilder.Entity("HBA.Financial.Billing.Domain.Commissions.CommissionRule", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
            b.Property<DateTime>("EffectiveFromUtc").HasColumnType("timestamp with time zone");
            b.Property<decimal>("FixedFee").HasColumnType("numeric(18,2)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<decimal?>("MaxFee").HasColumnType("numeric(18,2)");
            b.Property<decimal?>("MinFee").HasColumnType("numeric(18,2)");
            b.Property<decimal>("Rate").HasColumnType("numeric(6,4)");
            b.Property<string>("Scope").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<Guid?>("TargetId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("IsActive");
            b.HasIndex("Scope", "TargetId");
            b.ToTable("commission_rules", "billing");
        });

        modelBuilder.Entity("HBA.Financial.Billing.Domain.Invoices.Invoice", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)");
            b.Property<DateTime?>("IssuedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("PeriodEndUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("PeriodStartUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid>("SellerId").HasColumnType("uuid");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<decimal>("TotalAmount").HasColumnType("numeric(18,2)");
            b.HasKey("Id");
            b.HasIndex("SellerId");
            b.ToTable("invoices", "billing");
        });

        modelBuilder.Entity("HBA.Financial.Billing.Domain.Invoices.InvoiceLine", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<decimal>("Amount").HasColumnType("numeric(18,2)");
            b.Property<string>("Description").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
            b.Property<Guid>("InvoiceId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("InvoiceId");
            b.ToTable("invoice_lines", "billing");
        });

        modelBuilder.Entity("HBA.Financial.Billing.Domain.Invoices.InvoiceLine", b =>
        {
            b.HasOne("HBA.Financial.Billing.Domain.Invoices.Invoice", null)
                .WithMany("Lines")
                .HasForeignKey("InvoiceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("HBA.Financial.Billing.Domain.Invoices.Invoice", b =>
        {
            b.Navigation("Lines");
        });
#pragma warning restore 612, 618
    }
}
